spring:
  application:
    name: gxd-components-es
  http:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 4000MB
    encoding:
      force:  true
      charset:  UTF-8
      enabled:  true
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
logging:
  config: classpath:conf/log4j2.xml