server:
  port: 8000
logging:
    level:
        tk.mybatis: DEBUG

spring:
    datasource:
        name: geekcattle
        url: jdbc:mysql://localhost:3306/geekcattle
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mapper:
      plugin: tk.mybatis.mapper.generator.MapperPlugin

    application:
      name: gxd-consumer-permission
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      encoding: UTF-8
      mode: LEGACYHTML5

feign:
  httpclient:
    enabled: true
  #hystrix:
    #enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #???1000

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  config: classpath:conf/log4j2.xml

