spring:
  application:
    name: gxd-gateway-zuul
server:
  port: 8040
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  http://localhost:1111/eureka/
    registry-fetch-interval-seconds:  5 #对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
zuul:
  routes:
    wx:
      path: /wx/**
      serviceId:  gxd-consumer-freemarker
    news:
      path: /news/**
      serviceId:  gxd-consumer-freemarker