spring:
  application:
    name: gxd-gateway-zuul
server:
  port: 8040
eureka:
  instance:
    hostname: localhost   # 指定该Eureka实例的主机名
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  http://localhost:1111/eureka/