server:
  port: 12222
spring:
  application:
    name: gxd-config-server
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/liangliang1259/thoth-config-repository.git
          searchPaths:  respo
      label:  v1.0
          password: jing517li
          username: gongjing2012

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:1111/eureka/