server:
  port: 1113
info:
  component: hostname 192.168.50.37 to fetch configuration
spring:
    profiles:
      active: dev
    application:
      name: gxd-eureka-server
eureka:
 # begin  配置关闭自我保护，并配置Eureka Server清理无效节点的时间间隔
  server:
    hostname: 192.168.50.37:1113
    enable-self-preservation: false         # 设为false，关关闭自我保护，可以定期清理失效的服务
    eviction-interval-timer-in-ms: 1000   # 清理间隔（单位毫秒，默认是60*1000）
  # end
  instance:
    perferIpAddress: true
    leaseRenewalIntervalInSeconds: 10 #租期更新时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 30 #租期到期时间（默认90秒）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true #由于该应用为注册中心，所以设置为false, 代表不向注册中心注册自己
    fetchRegistry: true # 不需要从eureka服务器获取注册信息,由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为false
    serviceUrl:
      defaultZone: http://192.168.50.35:1111/eureka/,http://192.168.50.36:1112/eureka/ #指定服务注册中心的地址
logging:
  config: classpath:conf/log4j2.xml