server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: gxd-provider
  zipkin:
    base-url: http://gxd-zipkin-server:9411
  redis:
    # database: 0
    hostName: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 0
    pool:
      maxTotal: 30 # 控制一个pool可分配多少个jedis实例
      maxIdle: 10 # 最大能够保持idel状态的对象数
      minIdle: 5 # 最小能够保持idel状态的对象数
      maxWaitMillis: 3000 # 表示当borrow一个jedis实例时，最大的等待时间，如果超过等待时间，则直接抛出JedisConnectionException
      timeBetweenEvictionRunsMillis: 30000 # 多长时间检查一次连接池中空闲的连接
      minEvictableIdleTimeMillis: 30000 # 空闲连接多长时间后会被收回, 单位是毫秒
      testOnCreate: true # 当调用create Object方法时，是否进行有效性检查
      testOnBorrow: true # 当调用borrow Object方法时，是否进行有效性检查
      testOnReturn: true # 当调用return Object方法时，是否进行有效性检查
      testWhileIdle: true # 当调用test idle方法时，是否进行有效性检查

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

#management:
  #security:
     #enabled: false

logging:
  config: classpath:conf/log4j2.xml

druid:
  datasource:
    initialSize: 5
    maxActive: 10
    minIdle: 5
    maxWait: 60000
    useUnfairLock: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    filters: stat,wall,log4j
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    validationQuery: SELECT 1

custom:
  datasource:
    names: db1,db2
    db1:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456
      validationQuery: SELECT 1
    db2:
      url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456
      validationQuery: SELECT 1

mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.gxd.model

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
