server:
  port: 2001
spring:
  application:
    name: gxd-hystrix
  zipkin:
    base-url: http://gxd-zipkin-server:9411
  sleuth:
     #监控开关
    enabled: true
     #采样率
    sampler:
      percentage: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/,http://127.0.0.1:1112/eureka/,http://127.0.0.1:1113/eureka/

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #ȱʡΪ1000
  stream:
    dashboard:
      intervalInMilliseconds: 2000

gxd-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  config: classpath:conf/log4j2.xml