server:
  port: 2001
spring:
  application:
    name: gxd-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #ȱʡΪ1000
  stream:
    dashboard:
      intervalInMilliseconds: 2000

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  config: classpath:conf/log4j2.xml