server:
  port: 8012
spring:
  rocketmq:
    namesrvAddr:  192.168.50.36:9876;192.168.50.37:9876
    instanceName: reservation
    defaultProducer:  defaultProducer
    transactionProducer:  transactionProducer
    defaultConsumer:  defaultConsumer
    orderConsumer:  orderConsumer
    defaultTopic: test
    orderTopic: order
    maxMessageSize: 131072 # 1024*128 消息最大长度
    sendMsgTimeout: 10000 #发送消息超时时间
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumerMessageBatchMaxSize:  1

#rocketmq:
#  producer:
## 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
#    groupName: vehicleProducerGroup
#    #mq的nameserver地址
#    namesrvAddr:  127.0.0.1:9876  # 123.206.175.47:9876;182.254.210.72:9876
#    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
#    instanceName: vehicleProducer
#    #topic名称
#    topic: TEST
#    #根据实际情况设置消息的tag
#    tag: verifycode
#    #消息最大长度
#    maxMessageSize: 131072 # 1024*128
#    #发送消息超时时间
#    sendMsgTimeout: 10000
#  consumer:
#    namesrvAddr: 127.0.0.1:9876 #123.206.175.47:9876;182.254.210.72:9876
#    groupName: vehicleProducerGroup
#    topic: TEST
#    tag: verifycode
#    consumeThreadMin: 20
#    consumeThreadMax: 64
#    consumerMessageBatchMaxSize:  1
logging:
  config: classpath:conf/log4j2.xml