server:
  port: 2031
spring:
  application:
    name: gxd-components-redis
  redis:
    #数据库索引
      database: 0
      #服务器地址
      host: 127.0.0.1
      #服务器连接端口
      port: 6379
      #链接密码
      password: 123456
      #最大连接数（负值表示没有限制）
      max-active: 200
      #最大空闲链接
      max-idle: 50
      #最大阻塞等待时间（负值表示没有限制）
      max-wait: 200
      #最小空闲链接
      min-idle: 10
      master: 0
      #链接超时时间（毫秒）
      timeout: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
#spring:
##redis配置
#  redis:
#    cluster:
#      nodes:
##        - 192.168.2.10:7000
##        - 192.168.2.10:7001
##        - 192.168.2.10:7002
##        - 192.168.2.10:7003
##        - 192.168.2.10:7004
##        - 192.168.2.10:7005
#        - 192.168.50.36:7000
#        - 192.168.50.36:7001
#        - 192.168.50.36:7002
#        - 192.168.50.36:7007
#        - 192.168.50.36:7009
#        - 192.168.50.37:7003
#        - 192.168.50.37:7004
#        - 192.168.50.37:7005
#        - 192.168.50.37:7006
#        - 192.168.50.37:7008
logging:
  config: classpath:conf/log4j2.xml