server:
  port: 8081
info:
  component: sso-server to fetch configuration
spring:
  application:
    name: gxd-sso-client
  zipkin:
    base-url: http://GXD-ZIPKIN-SERVER:9411
  freemarker:
    request-context-attribute: request
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates
    settings.template_update_delay: 0
    settings.default_encoding: UTF-8
    settings.classic_compatible: true
    order: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
logging:
  config: classpath:conf/log4j2.xml
cookie:
  maxAge: 604800
  validKey: valid_key
services:
  auth: http://localhost:8080/login