server:
  port: 2032
spring:
  application:
    name: gxd-sso
#  redis:
#          #服务器地址
#    host: 127.0.0.1
#          #服务器连接端口
#    port: 6379
#         # 登录redis服务器的密码。
#    password: 123456
#    pool:
#      max-active: 200
#        # 池在给定时间可以分配的最大连接数。使用负值无限制。
#      max-idle: 50
#        # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。
#      max-wait: 200
#        # 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
#      min-idle: 10
#      master: 0
#          #链接超时时间（毫秒）
#    timeout: 3000
#        # 启用SSL支持。
#    ssl: false
  redis:
    cluster:
      nodes:
        - 192.168.50.36:7000
        - 192.168.50.36:7001
        - 192.168.50.36:7002
        - 192.168.50.36:7007
        - 192.168.50.36:7009
        - 192.168.50.37:7003
        - 192.168.50.37:7004
        - 192.168.50.37:7005
        - 192.168.50.37:7006
        - 192.168.50.37:7008
      timeout:  3000
      max-redirects:  5
      ssl: false
  freemarker:
      request-context-attribute: request
      allow-request-override: false
      allow-session-override: false
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
      prefer-file-system-access: true
      suffix: .ftl
      template-loader-path: classpath:/templates/
      settings.template_update_delay: 0
      settings.default_encoding: UTF-8
      settings.classic_compatible: true
      order: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
logging:
  config: classpath:conf/log4j2.xml
